### PR TITLE
Update 0079-configure-allow-user-to-build-FFmpeg-against-oneVPL.patch

### PR DESCRIPTION
**Pull request by xhaihao**
Add die message if libvpl is not available but --enable-libvpl is
specified.

### CODE REVIEW

**Review by uartie — APPROVED** [review]
LGTM.   Ignore the fate test failure (upstream issue).  Feel free to merge when ready.

**Comment by uartie** [comment]
FYI, fate is not executed on ffmpeg-libvpl check... this is why those pass the check ;)

**Comment by uartie** [comment]
I guess we need to use intel-media-ci user to override merge with failed checks.  Doing it now.

**Comment by xhaihao** [comment]
Thanks Artie

**Pull request merged**
