### PR TITLE
fix conficts for overlay_vaapi and vulkan

### PR DESCRIPTION
**Pull request by wenbinc-Bin**
Fix conflicts between cartwheel and ffmpeg upstream.

### CODE REVIEW

**Comment by xhaihao** [comment]
@wenbinc-Bin please check the failure.

**Comment by xhaihao** [comment]
@wenbinc-Bin You should update the submodule to the latest FFmpeg master in your patch.

**Comment by xhaihao** [comment]
Please squash the two commits into one, otherwise user might get a bad commit.

**Comment by wenbinc-Bin** [comment]
> Please squash the two commits into one, otherwise user might get a bad commit.

Ok, Got it.

**Review by xhaihao — APPROVED** [review]

**Pull request merged**
