### PR TITLE
Update submodule and patchset

### PR DESCRIPTION
**Pull request by xhaihao**
Submodule ffmpeg 0c8741f819..617452ce2c

Modified 0056, deleted 0081, then renamed 0082-0088 to 0081-0087

Signed-off-by: Haihao Xiang <haihao.xiang@intel.com>

### CODE REVIEW

**Comment by xhaihao** [comment]
The deleted patch (0081) was merged into mainline FFmpeg.

**Comment by xhaihao** [comment]
@Bin-CI I can't assess the details, could you please check the link ?

**Comment by xhaihao** [comment]
I can access the details for failure now. According to the error log, the failure wasn't caused by this patch.

**Comment by uartie** [comment]
@xhaihao looks like submodule update does not track to remote tree (not our ref).  Did you accidentally commit after applied patches?

**Comment by xhaihao** [comment]
It is weird there was only one failure before forced-push. I'll check the reason.

**Comment by xhaihao** [comment]
All checks passed now.

**Review by uartie — APPROVED** [review]
LGTM

**Comment by xhaihao** [comment]
all checks passed now.

**Pull request merged**
