### PR TITLE
Remove redundant decodeHeader

### PR DESCRIPTION
**Pull request by wenbinc-Bin**
Remove redundant decodeHeader and also rearrange the code to use
suggest surface number to init decoder.

### CODE REVIEW

**Comment by wenbinc-Bin** [comment]
I see the check failed at "container - install deps". It seems not relate to my patch. @uartie , is it an accident error?

**Comment by uartie** [comment]
> I see the check failed at "container - install deps". It seems not relate to my patch. @uartie , is it an accident error?

Yes, it was a random network error in file transfer.  I have re-triggered the checks.

**Comment by xhaihao** [comment]
when MFXVideoDECODE_DecodeFrameAsync returns MFX_ERR_INCOMPATIBLE_VIDEO_PARAM, it means the allocated mfx surface is not suitable for the current frame, may we call  MFXVideoDECODE_DecodeHeader again when returning MFX_ERR_INCOMPATIBLE_VIDEO_PARAM from MFXVideoDECODE_DecodeFrameAsync ?

**Comment by wenbinc-Bin** [comment]
Hi @xhaihao. If it returns MFX_ERR_INCOMPATIBLE_VIDEO_PARAM, the function qsv_decode_preinit() will be called as well. This means new surfaces will be created according to the new parameter we get from MFXVideoDECODE_DecodeHeader.

**Comment by xhaihao** [comment]
I didn't see MFX_ERR_INCOMPATIBLE_VIDEO_PARAM in upstream master, also didn't see MFX_ERR_INCOMPATIBLE_VIDEO_PARAM in this patch, so I thought MFX_ERR_INCOMPATIBLE_VIDEO_PARAM wasn't handled. Now I see MFX_ERR_INCOMPATIBLE_VIDEO_PARAM in your another patch.

**Comment by wenbinc-Bin** [comment]
Miss an error return. Now update.

**Comment by uartie** [comment]
@xhaihao are all your comments/reviews satisfied now?

**Comment by uartie** [comment]
https://patchwork.ffmpeg.org/project/ffmpeg/patch/20210426030341.3274799-2-wenbin.chen@intel.com/

**Comment by wenbinc-Bin** [comment]
Hi @xhaihao , @xuguangxin.
Is there any more feedback on this patchset?

**Review by xhaihao — APPROVED** [review]
LTGM, thanks!

**Review by xuguangxin — COMMENTED** [review]
Why this pr need to change the name of other patches?
If this patch sent to upstream. could you provide an upstream review link?
thanks

**Comment by xhaihao** [comment]
Wenbin re-arrange the patchset, see the commit log. 

see https://github.com/intel-media-ci/cartwheel-ffmpeg/pull/32#issuecomment-854160966 for the upstream link.

**Comment by wenbinc-Bin** [comment]
Because I use the returned value to reinit codec, there are two old patches can be improved on the basis of this, so I regenerate them and rearrange the patch.

**Review by xuguangxin — APPROVED** [review]
haihao, U.Artie and wenbin thanks for the information

**Pull request merged**
