### PR TITLE
fix opencl crash issue and disable hwdevice test for qsv->vaapi->qsv.

### PR DESCRIPTION
**Pull request by xuguangxin**

### CODE REVIEW

**Comment by uartie** [comment]
test regressions caused by https://github.com/Intel-Media-SDK/MediaSDK/issues/2622

**Comment by xuguangxin** [comment]
Thanks @uartie for the investigation. I also found following errors in ci log, is them important?
```
00:30:31,000 WARN  - cp: cannot stat '64M': No such file or directory
00:30:31,001 WARN  - cp: -r not specified; omitting directory 'fate'
00:30:31,002 WARN  - cp: -r not specified; omitting directory 'filtergraphs'
00:30:31,003 WARN  - cp: -r not specified; omitting directory 'images'
00:30:31,004 WARN  - cp: -r not specified; omitting directory 'lavf'
00:30:31,005 WARN  - cp: -r not specified; omitting directory 'lavf-fate'
00:30:31,006 WARN  - cp: -r not specified; omitting directory 'pixfmt'
```

**Comment by uartie** [comment]
> Thanks @uartie for the investigation. I also found following errors in ci log, is them important?
> 
> ```
> 00:30:31,000 WARN  - cp: cannot stat '64M': No such file or directory
> 00:30:31,001 WARN  - cp: -r not specified; omitting directory 'fate'
> 00:30:31,002 WARN  - cp: -r not specified; omitting directory 'filtergraphs'
> 00:30:31,003 WARN  - cp: -r not specified; omitting directory 'images'
> 00:30:31,004 WARN  - cp: -r not specified; omitting directory 'lavf'
> 00:30:31,005 WARN  - cp: -r not specified; omitting directory 'lavf-fate'
> 00:30:31,006 WARN  - cp: -r not specified; omitting directory 'pixfmt'
> ```

those errors can be ignored for now... I will try to suppress them when I have time.

**Comment by xuguangxin** [comment]
sure,thanks

**Pull request merged**
