### PR TITLE
update submodule and rebase vpxenc dynamic res

### PR DESCRIPTION
**Pull request by uartie**
Signed-off-by: U. Artie Eoff <ullysses.a.eoff@intel.com>

### CODE REVIEW

**Comment by xhaihao** [comment]
Is vpxenc dynamic res used in our CI? if not, how about to remove this patch from patchset?

**Comment by uartie** [comment]
> Is vpxenc dynamic res used in our CI? if not, how about to remove this patch from the patchset?

I'm not sure which customer depends on it.  @xuguangxin?

For now, can we merge to unblock CI for everything else?

**Comment by xuguangxin** [comment]
No customer needs it, Lingjie just want to use it to prove we can support dynamic resolution change on the encoder. 
we can remove it if it's no regression to full round

**Comment by uartie** [comment]
I will merge this PR so we can unwedge the CI.  @xuguangxin please assign someone to do a bulk audit on which patches can be removed.  It can be submitted in separate PR.

**Comment by xuguangxin** [comment]
I think most cartwheel patches are lack review. We can ask someone to submit current cartwheel patches one by one to https://github.com/intel-media-ci/ffmpeg. Then we can review it :). 
If one patch is good for upstream, we can send it upstream, if not we can drop it.

**Pull request merged**
