### PR TITLE
Update submodule and patchset

### PR DESCRIPTION
**Pull request by xhaihao**
Submodule ffmpeg ad67ea9eee..2345b4eb9c

Update 0009, 0010, 0014, 0015, 0016, 0018, 0019, 0028, 0029, 0031,
0054, 0056, 0057, 0076, 0077

Signed-off-by: Haihao Xiang <haihao.xiang@intel.com>

### CODE REVIEW

**Comment by xhaihao** [comment]
@Bin-CI @FocusLuo  FFmpeg introduced VUYA for 4:4:4 format (see https://github.com/FFmpeg/FFmpeg/commit/6ab8a9d375ca922b2a94cd7160a4e3c5abe6339c), I removed  0yuv in this PR and used VUYA instead. Could you please update pre-check as well ?

**Comment by uartie** [comment]
> so this part will been change? https://github.com/intel/vaapi-fits/blob/master/lib/framereader.py#L126

No.  We should only need to change the mapping here: https://github.com/intel/vaapi-fits/blob/master/lib/ffmpeg/util.py#L60

**Comment by uartie** [comment]
@xhaihao pre-check patch is merged.  Can you check why 2 encode cases failed?

**Comment by uartie** [comment]
> @xhaihao pre-check patch is merged. Can you check why 2 encode cases still failed?

I see VUYA nb_components is 4, whereas 0YUV was 3...

**Comment by xhaihao** [comment]
> > @xhaihao pre-check patch is merged. Can you check why 2 encode cases still failed?
> 
> I see VUYA nb_components is 4, whereas 0YUV was 3...

Thanks for the finding, I updated the PR.

**Pull request merged**
