### PR TITLE
Update submodule and 0013/0030/0033

### PR DESCRIPTION
**Pull request by xhaihao**
This fixes the conflict when applying 0013, 0030 and 0033 to submodule
    b492cac
    
    Submodule ffmpeg d5b3e04..b492cac
    
    Signed-off-by: Haihao Xiang <haihao.xiang@intel.com>
    Signed-off-by: U. Artie Eoff <ullysses.a.eoff@intel.com>

### CODE REVIEW

**Comment by xhaihao** [comment]
@uartie It seems fate in pre-check was broken again.

**Comment by uartie** [comment]
> @uartie It seems fate in pre-check was broken again.

Seems fate was an intermittent failure or fixed.

However, there is a composite test (vaapi_overlay) that fails with this submodule update:
```
[AVFilterGraph @ 0x55c6998eecc0] Too many inputs specified for the "overlay_vaapi" filter.
```
Did some change in upstream break this plugin?

**Comment by uartie** [comment]
This commit https://github.com/FFmpeg/FFmpeg/commit/8be701d9f7f77ff2282cc7fe6e0791ca5419de70 ?

**Comment by uartie** [comment]
> This commit [FFmpeg/FFmpeg@8be701d](https://github.com/FFmpeg/FFmpeg/commit/8be701d9f7f77ff2282cc7fe6e0791ca5419de70) ?

Yep, this commit changes AVFilter/AVFilterPad semantics.  Thus, please update vf_overlay_vaapi.c (in patch 0030).  The below change fixes it for me.

```diff
diff --git a/libavfilter/vf_overlay_vaapi.c b/libavfilter/vf_overlay_vaapi.c
index 249e24cd4263..e0e583525d63 100644
--- a/libavfilter/vf_overlay_vaapi.c
+++ b/libavfilter/vf_overlay_vaapi.c
@@ -399,7 +399,6 @@ static const AVFilterPad overlay_vaapi_inputs[] = {
         .type             = AVMEDIA_TYPE_VIDEO,
         .get_buffer.video = ff_default_get_video_buffer,
     },
-    { NULL }
 };
 
 static const AVFilterPad overlay_vaapi_outputs[] = {
@@ -408,7 +407,6 @@ static const AVFilterPad overlay_vaapi_outputs[] = {
         .type          = AVMEDIA_TYPE_VIDEO,
         .config_props  = &overlay_vaapi_config_output,
     },
-    { NULL }
 };
 
 AVFilter ff_vf_overlay_vaapi = {
@@ -420,7 +418,7 @@ AVFilter ff_vf_overlay_vaapi = {
     .uninit          = &overlay_vaapi_uninit,
     .query_formats   = &overlay_vaapi_query_formats,
     .activate        = &overlay_vaapi_activate,
-    .inputs          = overlay_vaapi_inputs,
-    .outputs         = overlay_vaapi_outputs,
+    FILTER_INPUTS(overlay_vaapi_inputs),
+    FILTER_OUTPUTS(overlay_vaapi_outputs),
     .flags_internal  = FF_FILTER_FLAG_HWFRAME_AWARE,
 };
```

**Review by uartie — CHANGES_REQUESTED** [review]
Please update vaapi_overlay patch

**Comment by xhaihao** [comment]
OK, thanks for catching it, I'll update it ASAP.

**Comment by uartie** [comment]
Latest failure (avc to avc H2H transcode) is not caused by this patchset.  Same failure is also being observed on mainline recently.  It will be triaged in a different context.

**Review by uartie — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
