### PR TITLE
avutils/hwcontext_qsv: set the source device in qsv_devic_create

### PR DESCRIPTION
**Pull request by xuguangxin**

### CODE REVIEW

**Comment by uartie** [comment]
patch does not apply

**Comment by xuguangxin** [comment]
Thanks for check, fixed

**Comment by uartie** [comment]
@xuguangxin in our post-merge fate test results, this patch causes failure in hwdevice test.  Oddly, our pull-request pre-check fate test doesn't execute this test.  The difference is that in pre-check we run whole suite with `make fate` but in post-merge we run each fate case individually with `make <case>` for each `<case>` listed in `make fate-list`.  I will try to make it consistent in CI so all cases are executed equally.  In the meantime, can you check why this is failing with your patch and submit an update to fix it?  See line `Derivation qsv to vaapi succeeded, but derivation back again did not return the original device.`:
```
TEST    hwdevice
03:42:28,814 INFO  - ./tests/fate-run.sh fate-hwdevice "/opt/media/src/assets/otc-media/fate" "" "/opt/media/build/ffmpeg" 'run libavutil/tests/hwdevice' 'null' '' '' '1' '' '' '' '' '' '' '' '' '' '1'
03:42:28,817 INFO  -  /opt/media/build/ffmpeg/libavutil/tests/hwdevice
03:42:28,828 INFO  - Test hwdevice failed. Look at tests/data/fate/hwdevice.err for details.
03:42:28,828 INFO  - Device type vaapi successfully created.
03:42:28,828 INFO  - Successfully tested derivation vaapi -> qsv.
03:42:28,828 INFO  - Unable to derive vaapi -> drm: -38.
03:42:28,828 INFO  - Test passed for vaapi with default options.
03:42:28,828 INFO  - Device type vaapi successfully created.
03:42:28,828 INFO  - Successfully tested derivation vaapi -> qsv.
03:42:28,828 INFO  - Unable to derive vaapi -> drm: -38.
03:42:28,828 INFO  - Test passed for vaapi with device /dev/dri/renderD128.
03:42:28,828 INFO  - [AVHWDeviceContext @ 0x7f795c012080] No VA display found for device /dev/dri/renderD129.
03:42:28,828 INFO  - Failed to create vaapi device: -22.
03:42:28,828 INFO  - [AVHWDeviceContext @ 0x7f795c019800] No VA display found for device :0.
03:42:28,828 INFO  - Failed to create vaapi device: -22.
03:42:28,828 INFO  - Device type qsv successfully created.
03:42:28,828 INFO  - Derivation qsv to vaapi succeeded, but derivation back again did not return the original device.
03:42:28,828 INFO  - Test failed for qsv with default options.
03:42:28,828 INFO  - Failed to create drm device: -14.
03:42:28,828 INFO  - Device type drm successfully created.
03:42:28,828 INFO  - Successfully tested derivation drm -> vaapi.
03:42:28,828 INFO  - Unable to derive drm -> qsv: -38.
03:42:28,828 INFO  - Test passed for drm with device /dev/dri/card0.
03:42:28,828 INFO  - Failed to create drm device: -2.
03:42:28,828 INFO  - Device type drm successfully created.
03:42:28,828 INFO  - Successfully tested derivation drm -> vaapi.
03:42:28,828 INFO  - Unable to derive drm -> qsv: -38.
03:42:28,828 INFO  - Test passed for drm with device /dev/dri/renderD128.
03:42:28,828 INFO  - Failed to create drm device: -2.
03:42:28,828 INFO  - Attempted to test 3 device types: 2 passed, 1 failed, 0 skipped.
03:42:28,828 INFO  - tests/Makefile:255: recipe for target 'fate-hwdevice' failed
03:42:28,828 INFO  - make: *** [fate-hwdevice] Error 1
```

**Comment by uartie** [comment]
The other difference is that we set LIBVA_DRIVER_NAME in post-merge execution, but don't set it in pre-check execution.

**Comment by uartie** [comment]
Aha, in fate makefile:
```
# Tests requiring hardware support are not included in a default fate run.
```
... thus, hw tests don't get run with `make fate`, but `make fate-list` will still list them.

I will add `make fate-hw` to pre-check also.

**Comment by xuguangxin** [comment]
@uartie , Great!
After you added make fate-hw, I do not need get fate clips by my self. I just need send pr to check the fate result, right?
thanks

**Comment by uartie** [comment]
Yes, you can submit a PR now.  I will add `make fate-hw` tomorrow after @xhaihao fixes/merges last rebase issue.  Then I will ensure your PR is run with updated pre-check.

**Comment by uartie** [comment]
You might be able to run `make fate-hwdevice` locally without getting the fate clips.  I don't think this test requires the clips.

**Comment by xuguangxin** [comment]
thanks, I can reproduce using `make fate-hwdevice V=2`, let me speed time check why it's failed. You can revert the patch temporally. 

thanks

**Comment by uartie** [comment]
Reverted in #12

**Comment by uartie** [comment]
I have added `make fate-hw` step to CI pre-check.

**Comment by xuguangxin** [comment]
Hi @uartie ,
Thanks.
Will this step do the decode/encode things?
Some clips (maybe more)in fate will fail the hardware decode. The comunity has a fix, but it's not merged. 
See:
https://patchwork.ffmpeg.org/project/ffmpeg/patch/20210309023600.16661-1-jamrial@gmail.com/#62813

**Comment by uartie** [comment]
AFAICT, there is only one HW test in fate, `fate-hwdevice`.  I think all other tests are just SW.

**Comment by xuguangxin** [comment]
Great!
I have found the root cause of this issue. It's not a big thing,  we may 
need change the hwdevcide test after we got the feedback at
https://patchwork.ffmpeg.org/project/ffmpeg/patch/20210222084504.339978-1-guangxin.xu@intel.com/#62824

thanks for founding this issue.

**Pull request merged**
