### PR TITLE
WIP:vaapi: use xyuv instead of ayuv

### PR DESCRIPTION
**Pull request by xhaihao**
https://github.com/intel/media-driver/pull/1144 and https://github.com/intel/libva/pull/442/ are needed for testing.

### CODE REVIEW

**Comment by uartie** [comment]
Please remove submodule update.

Does this mean AYUV is no longer a valid option for the user if VA_FOURCC_XYUV is defined?

Also, since this uses 0YUV, it is not upstreamable because 0YUV has not been accepted.  Can you resolve/resurrect the conversation in upstream?

**Comment by xhaihao** [comment]
> Please remove submodule update.

Thanks for catching it. I thought I have clean the submoulde before creating the patch, I will update the patch. 

> Does this mean AYUV is no longer a valid option for the user if VA_FOURCC_XYUV is defined?

Yes, but from the perspective of FFmpeg, user always uses 0yuv. I will totally remove AYUV in the final version, currently this patch is for testing only. 

> Also, since this uses 0YUV, it is not upstreamable because 0YUV has not been accepted. Can you resolve/resurrect the conversation in upstream?

Actually 0yuv is suggested by community. We will resend the corresponding patches once xyuv are merged into libva / media drive and msdk. 

BTW is it better to name it as xyuv instead of 0yuv? If so, we may use xyuv from upper layer to lower layer. However in FFmpeg, 0rgb instead of xrgb was added in the past.

**Comment by uartie** [comment]
> > Please remove submodule update.
> 
> Thanks for catching it. I thought I have clean the submoulde before creating the patch, I will update the patch.
> 

Easy mistake... I do it all the time 😄 

> > Does this mean AYUV is no longer a valid option for the user if VA_FOURCC_XYUV is defined?
> 
> Yes, but from the perspective of FFmpeg, user always uses 0yuv. I will totally remove AYUV in the final version, currently this patch is for testing only.
> 

Ah, yes, you're right.  I forgot we already map the common use of AYUV to 0yuv in our test suite for ffmpeg.

> > Also, since this uses 0YUV, it is not upstreamable because 0YUV has not been accepted. Can you resolve/resurrect the conversation in upstream?
> 
> Actually 0yuv is suggested by community. We will resend the corresponding patches once xyuv are merged into libva / media drive and msdk.
> 

Great!  I hope the community finally accepts it.

> BTW is it better to name it as xyuv instead of 0yuv? If so, we may use xyuv from upper layer to lower layer. However in FFmpeg, 0rgb instead of xrgb was added in the past.

I guess if community already likes 0yuv (and 0rgb), then best to keep them happy 😉.

**Comment by uartie** [comment]
what's the status of this PR?

**Comment by xhaihao** [comment]
I will provide a patch to add 0yuv in FFmpeg, currently I am working on another task. let's close this PR.

**Pull request closed without merging**
