### PR TITLE
avcodec/dxva2_av1.c: fix global motion params

### PR DESCRIPTION
**Pull request by tong1wu**
Defined in spec 5.9.24/5.9.25. Since function void
global_motion_params(AV1DecContext *s) already updates
gm type/params, the wminvalid parameter only need to get
the value from cur_frame.gm_invalid.

### CODE REVIEW

**Comment by tong1wu** [comment]
@xhaihao please review, to see whether it can be merged into cartwheel

**Comment by uartie** [comment]
Have you tried submitting to upstream, first?

**Comment by xhaihao** [comment]
@tong1wu It would be better to update Fei's patch to fix this issue in cartwheel.

**Comment by uartie** [comment]
> @tong1wu It would be better to update Fei's patch to fix this issue in cartwheel.

agree with @xhaihao

**Comment by tong1wu** [comment]
> @tong1wu It would be better to update Fei's patch to fix this issue in cartwheel.

@xhaihao this patch is related to fei's patches 0087 and 0088. 0087 is for common part and 0088 is for vaapi. This patch is for dxva2 so it might be clear to separate them.

**Comment by xhaihao** [comment]
@tong1wu could you re-create this patch against the latest master branch ? You may use 0093 as prefix now.

**Comment by tong1wu** [comment]
@xhaihao thanks, already updated

**Comment by xuguangxin** [comment]
> > Have you tried submitting to upstream, first?
> > @uartie No, since @feiwan1‘s patch about global motion is still in cartwheel, after we discussed, it might be better to put it in here first.

@feiwan1 , any issue to block the upstream?

**Comment by feiwan1** [comment]
James thought my previous change is just for vaapi, it should not add vaapi only thing into av1dec common part. Maybe wutong can submit your patch into community and explain it is depend on my not merged patch and ping James to merge them together if no objection because now we have 2 hw decoder need it.

**Comment by xuguangxin** [comment]
@feiwan1  checked James's comment, It's not related to this. 
He objects because we do some vaapi specific things in the base class. Is it possible to do it in vaapi only?
thanks

**Comment by feiwan1** [comment]
@xuguangxin, Yes I can move the film grain references(patch 5~9) for vaapi from base class to vaapi as we talked before. It's also in my plan. Now wutong's patch is depend on my patch(1~4) which doesn't change. So that I said wutong can submit his patch now. Or do you wish to submit it together with my patch set after I modified patch 5~9 ?

**Comment by xuguangxin** [comment]
yes. @tong1wu  can wait for your patch upstreamed.

**Pull request merged**
