### PR TITLE
Update submodule and patchset

### PR DESCRIPTION
**Pull request by xhaihao**
Submodule ffmpeg 155dcfe2e2..ed6c5c13b1
Modified 0002, 0011, 0034, 0075
Deleted 0051, 0090
Renamed 0052 ~ 0089 to 0051 ~ 0088

### CODE REVIEW

**Comment by xhaihao** [comment]
The failures are caused by commit 131dbb9a7a2dd645c36a85190e2fe0ab987c45cf. I'm curious why this change wasn't caught by our CI.

**Comment by uartie** [comment]
> The failures are caused by commit 131dbb9a7a2dd645c36a85190e2fe0ab987c45cf. I'm curious why this change wasn't caught by our CI.

Yes, that's odd... maybe it's an intermittent ffprobe trailing `x` on resolution output?  Anyhow, I have submitted patch to handle this case in our test suite: https://github.com/intel/vaapi-fits/commit/5cb1f4979e04d3344a487dd7b9f550c806827788

**Comment by uartie** [comment]
> > The failures are caused by commit 131dbb9a7a2dd645c36a85190e2fe0ab987c45cf. I'm curious why this change wasn't caught by our CI.
> 
> Yes, that's odd... maybe it's an intermittent ffprobe trailing `x` on resolution output? Anyhow, I have submitted patch to handle this case in our test suite: [intel/vaapi-fits@5cb1f49](https://github.com/intel/vaapi-fits/commit/5cb1f4979e04d3344a487dd7b9f550c806827788)

Actually, it looks like our CI did catch this in several mainline/cartwheel test runs... but other recent regressions are causing too much noise so we did not see it.

**Comment by uartie** [comment]
@xhaihao please check why fate fails. Are you able to reproduce?  FYI, we only run fate in ffmpeg-libmfx PR check (not ffmpeg-libvpl).

**Comment by xhaihao** [comment]
> @xhaihao please check why fate fails. Are you able to reproduce? FYI, we only run fate in ffmpeg-libmfx PR check (not ffmpeg-libvpl).

Sorry, I missed the fate error and thought the failures were all caused by commit 131dbb9a7a2dd645c36a85190e2fe0ab987c45cf

**Comment by xhaihao** [comment]
commit d6176eeeec1458ea2c9a027d394619c754086827 disallow the coexistence of AV_CODEC_CAP_FRAME_THREADS and AV_CODEC_CAP_ENCODER_FLUSH.  0011 added AV_CODEC_CAP_ENCODER_FLUSH to ff_rawvideo_encoder, however recently AV_CODEC_CAP_FRAME_THREADS was added to ff_rawvideo_encoder recently. I'll remove AV_CODEC_CAP_ENCODER_FLUSH from ff_rawvideo_encoder temporarily.

**Pull request merged**
